version: 2

project_name: mnemosyne

before:
  hooks:
    - task download-darwin-libs

env:
  - CGO_ENABLED=1

builds:
  - id: "darwin"
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-Llib/darwin_{{ .Arch }} -Flib/darwin_{{ .Arch }} -L{{ .Env.SDK_PATH }}/usr/lib -F{{ .Env.SDK_PATH }}/System/Library/Frameworks
      - CGO_CFLAGS=-Iinclude -isysroot {{ .Env.SDK_PATH }}
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -w -X github.com/gandazgul/mnemosyne/cmd.Version={{.Version}} -X github.com/gandazgul/mnemosyne/cmd.Commit={{.Commit}} -X github.com/gandazgul/mnemosyne/cmd.Date={{.Date}} -X github.com/gandazgul/mnemosyne/cmd.Release=true

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
